---
dependencies: []

galaxy_info:
  author: lesmyrmidons
  description: NVidia Installer
  company: ""
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  categories:
    - development
    - system