---
- name: register CUDA repository
  shell: {{cuda_fetch_deb}} && dpkg -i {{cuda_deb}}

- name: install CUDA
  apt: name=cuda update_cache=yes

- name: write environmant variables to bash profile
  copy: src=./cuda.sh dest=/etc/profile.d/